stages:
  data_ingestion:
    cmd: python src/ZillowHouseData/pipeline/stage_01_data_ingestion_pipeline.py
    deps:
      - src/ZillowHouseData/pipeline/stage_01_data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion


  data_preprocessing:
    cmd: 
      - python src/ZillowHouseData/pipeline/stage_02_data_preprocessing_pipeline.py
    deps:
      - src/ZillowHouseData/pipeline/stage_02_data_preprocessing_pipeline.py
      - config/config.yaml
      - artifacts/data_ingestion
    # outs:
    #   - artifacts/data_ingestion

  model_training:
    cmd:
      - python src/ZillowHouseData/pipeline/stage_03_model_training_pipeline.py
    deps:
      - src/ZillowHouseData/pipeline/stage_03_model_training_pipeline.py
      - artifacts/data_ingestion
      - config/config.yaml
    params:
      - LEARNING_RATE
      - EPOCHS
      - BATCH_SIZE
      - VALIDATION_SPLIT
      - VERBOSE
    outs:
      - artifacts/models

  model_evaluation:
    cmd:
      - python src/ZillowHouseData/pipeline/stage_04_model_evaluate_pipeline.py
    deps:
      - src/ZillowHouseData/pipeline/stage_04_model_evaluate_pipeline.py
      - config/config.yaml
      - artifacts/models
      - artifacts/data_ingestion

    