stages:
  data_ingestion:
    cmd: python src/ZillowHouseData/pipeline/stage_01_data_ingestion.py
    deps:
      - src/ZillowHouseData/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion