# FILE_NAME: ZILLOW_DATA_962c837a6ccefddddf190101e0bafdaf.csv
# START_DATE: 2012-01-01
# INTERESTED_COLUMNS: ['indicator_id', 'region_id', 'date', 'value']
# INTERESTED_INDICATORS_STATS: ['IRAM', 'CRAM', 'MRAM', 'LRAM', 'NRAM', 'SRAM']
# INTERESTED_INDICATORS_ZHVI: ['ZATT', 'ZSFH', 'ZALL', 'ZCON', 'ZABT', 'Z2BR', 'Z5BR', 'Z3BR', 'Z1BR', 'Z4BR']
# USER_INPUT_REQS: ['encoded_indicator_id','region_id','year','month','CRAM','IRAM','LRAM','MRAM','NRAM','SRAM']
LEARNING_RATE: 0.001
EPOCHS: 1
BATCH_SIZE: 32
VALIDATION_SPLIT: 0.1
VERBOSE: 2
