LEARNING_RATE: 0.001
EPOCHS: 1
BATCH_SIZE: 32
VALIDATION_SPLIT: 0.1
VERBOSE: 2

# MAX_DEPTH: 3
# LEARNING_RATE: 0.1
# REG_ALPHA: 0.01
# REG_LAMBDA: 1
# MIN_CHILD_WEIGHT: 1
# OBJECTIVE: 'reg:squarederror'
# EVAL_METRIC: rmse
# N_ESTIMATORS: 100
# RANDOM_STATE: 42
