artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1WqpLl5PbrhODaj4WuBB5tDvNCpQDm8MW/view
  local_data_file: artifacts/data_ingestion/zillow_files.zip
  unzip_dir: artifacts/data_ingestion

data_preprocessing:
  stats_path: ./artifacts/data_ingestion/stats.csv
  final_csv_path: ./artifacts/data_ingestion/final.csv
  file_name: ZILLOW_DATA_962c837a6ccefddddf190101e0bafdaf.csv
  region_file_name: ZILLOW_REGIONS_1a51d107db038a83ac171d604cb48d5b.csv
  start_date: 2012-01-01
  interested_columns: ['indicator_id', 'region_id', 'date', 'value']
  interested_indicators_stats: ['IRAM', 'CRAM', 'MRAM', 'LRAM', 'NRAM', 'SRAM']
  interested_indicators_zhvi: ['ZATT', 'ZSFH', 'ZALL', 'ZCON', 'ZABT', 'Z2BR', 'Z5BR', 'Z3BR', 'Z1BR', 'Z4BR']

model_training:
  final_csv_path: ./artifacts/data_ingestion/final.csv

model_evaluate:
  mlflow_uri: "https://dagshub.com/MurariHarish/Zillow-data-ML-project.mlflow"
  
user_predict:
  user_input_reqs: ['encoded_indicator_id','region_id','year','month','CRAM','IRAM','LRAM','MRAM','NRAM','SRAM']